package symbols

const (
	CookieName             = "capitan"
	Username               = "username"
	Password               = "password"
	Old                    = "old"
	New                    = "new"
	Key                    = "key"
	IP                     = "ip"
	Gateway                = "gateway"
	Confirmation           = "confirmation"
	Question               = "question"
	Answer                 = "answer"
	IsAdmin                = "is-admin"
	IsEnabled              = "is-enabled"
	Interface              = "interface"
	CaptureName            = "capture-name"
	Description            = "description"
	Script                 = "script"
	File                   = "file"
	ErrorResponse          = "error"
	UpdateGraphsResponse   = "update-graphs"
	UpdateStreamCountGraph = "stream-type-graph"
	UpdateLayer4Graph      = "layer-4-graph"
	UpdateHostCountGraph   = "host-packet-count"
	UpdateTopologyGraph    = "topology"
	PacketResponse         = "packet"
	StreamResponse         = "stream"
	HostResponse           = "host"
	StopSignal             = "STOP"
)
